In [56]:
import numpy as np
import pandas as pd
import matplotlib as plot

In [57]:
#QUESTION 1

#Assigns x
x = 26

#Assigns y array
y = [2, 36, 1, 98, 124]

#Assigns z as x * y
z = [2 * x, 36 * x, 1 * x, 98 * x, 124 * x]

print(z)

[52, 936, 26, 2548, 3224]


In [58]:
#QUESTION 2

#Assigns variables
x = 21
y = 2
Q2_1 = [x]
Q2_2 = [y]

#Builds series array from 21 to 400
while x < 400:
    x = Q2_1[-1] + 1
    Q2_1 = Q2_1 + [x]

#Builds series array from 2 to -35
while y > -35:
    y = Q2_2[-1] - 1
    Q2_2 = Q2_2 + [y]

print(Q2_1)
print(Q2_2)

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236

In [59]:
#QUESTION 3

#Assigns variables
x = -3
Q3 = [x]

#Builds series array from -3 to 9
while x < 9:
    x = Q3[-1] + 0.1
    x = round(x, 1) #Ensures x stays at 1 decimal point
    Q3 = Q3 + [x]

print(Q3)

[-3, -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2.0, -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0]


In [60]:
#QUESTION 4

i = 0 #index
n = len(Q3) #determines max random number
Q4 = np.zeros((100,20)) #makes 

while i < 100: #Repeats the random sampling 100 times
    j = 0 #index

    while j < 20: #randomly samples 20 elements from Q3
        Q4[i][j] = Q3[np.random.randint(0,len(Q3))]
        j += 1
    
    i += 1

print(Q4)


[[ 8.5 -1.5  3.4 ...  8.9  2.3  4.1]
 [ 1.8  3.8 -0.1 ...  4.8 -0.4  0.6]
 [ 6.9  7.  -2.2 ...  7.2  4.2  8.3]
 ...
 [ 7.7  6.8 -2.2 ...  2.3 -1.2  6.7]
 [ 5.3 -0.4  7.1 ...  1.6  4.4 -1.9]
 [ 5.2  4.3  1.1 ... -2.3 -1.7  1.4]]


In [61]:
#QUESTION 5

#I'm interpreting this as needing a 6x6 dataframe with the columns titled by the days and the rows titled by the numbers.

t = ["mon", "tue", "wed", "thu", "fri", "sat"] #column titles
m = [90, 80, 50, 20, 5, 20] #row titles

Q5 = pd.DataFrame(np.zeros((6,6)), m, t) #creates a 6x6 dataframe that uses the information in lists t & m

print(Q5)

    mon  tue  wed  thu  fri  sat
90  0.0  0.0  0.0  0.0  0.0  0.0
80  0.0  0.0  0.0  0.0  0.0  0.0
50  0.0  0.0  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0


In [62]:
#QUESTION 6

class w: #weight stats
    weight = np.empty(100) #creates empty array
    mean = 81
    sd = 0.26
    units = "kg"

class h: #height stats
    height = np.empty(100) #creates empty array
    mean = 1.76
    sd = 0.22
    units = "m"

class a: #age stats
    age = np.empty(100) #creates empty array
    mean = 25
    sd = 5
    units = "years"

gender = np.empty(100, str)
genderOpts = ["A", "B", "C"]

for i in range(100):
    w.weight[i] = np.random.normal(w.mean, w.sd)
    h.height[i] = np.random.normal(h.mean, h.sd)
    a.age[i] = np.random.normal(a.mean, a.sd)
    gender[i] = genderOpts[np.random.randint(0,len(genderOpts))] #randomly samples from list ["A", "B", "C"]

print(w.weight)
print(h.height)
print(a.age)
print(gender)
    

[80.92693917 80.82325716 80.18800092 81.2588342  80.67532857 81.53118309
 81.05567846 81.38826303 80.71117564 81.25754155 81.23744128 81.03228662
 80.78195652 80.78429134 80.70639974 81.21133812 80.812142   80.70121008
 81.01539363 80.75925365 81.35988904 80.9585397  81.07405067 81.29980964
 80.91974265 81.05376647 80.92655414 81.48424158 81.14468481 80.64105936
 81.86357178 80.75143988 81.62654927 80.9660439  80.84373654 81.04713688
 81.08254831 80.65866992 81.07361983 81.11490583 81.09740607 80.88764064
 80.43506791 81.52139191 81.0015134  80.95165429 81.2279219  80.90738811
 80.74015204 81.1319613  80.56340326 80.89881275 81.13541501 81.32839249
 80.806019   80.85350944 81.06610753 81.21323211 81.22158937 81.31398626
 80.83755093 81.11921051 80.71450106 81.14120223 80.65497199 80.99947378
 81.11627307 81.12423213 81.10523433 80.88818187 80.91437019 80.87730906
 80.96322332 80.6081683  81.05987079 81.07718594 80.68388004 81.19228326
 80.60033228 81.21495536 80.89166901 80.914213   80

In [65]:
#QUESTION 7

BMI = np.full(100, np.nan) #generates 100 element array of NaN

Q7 = pd.DataFrame({ #Organizes the data by column in this dataframe
    "Weight": w.weight, 
    "Height": h.height, 
    "Age": a.age, 
    "Gender": gender,
    "BMI": BMI
    }
)

print(Q7)

       Weight    Height        Age Gender  BMI
0   80.926939  1.311158  19.340225      C  NaN
1   80.823257  1.753769  16.441907      C  NaN
2   80.188001  2.049443  20.067738      B  NaN
3   81.258834  1.635225  27.433182      A  NaN
4   80.675329  1.897708  28.800292      B  NaN
..        ...       ...        ...    ...  ...
95  80.778257  1.893169  20.096202      B  NaN
96  81.001885  1.523962  24.684758      C  NaN
97  81.022949  1.717237  20.507163      C  NaN
98  81.462898  1.833087  22.679948      A  NaN
99  80.942447  1.476627  29.979698      C  NaN

[100 rows x 5 columns]


In [ ]:
#QUESTION 8

AgeGroup = np.empty(100, 'U8') #creates array of 8 character strings

for i in range(100): 
    temp = Q7.at[i, "Age"] #references the ages 1 by 1

    if temp < 20:
        AgeGroup[i] = "Under 20"
    elif temp > 30:
        AgeGroup[i] = "Over 30"
    else:
        AgeGroup[i] = "20 to 30"

Q8 = Q7.copy() #copies Q7
Q8["Age group"] = AgeGroup #Adds column titled "Age group" to Q8

print(Q8)

       Weight    Height        Age Gender  BMI Age group
0   80.926939  1.311158  19.340225      C  NaN  Under 20
1   80.823257  1.753769  16.441907      C  NaN  Under 20
2   80.188001  2.049443  20.067738      B  NaN  20 to 30
3   81.258834  1.635225  27.433182      A  NaN  20 to 30
4   80.675329  1.897708  28.800292      B  NaN  20 to 30
..        ...       ...        ...    ...  ...       ...
95  80.778257  1.893169  20.096202      B  NaN  20 to 30
96  81.001885  1.523962  24.684758      C  NaN  20 to 30
97  81.022949  1.717237  20.507163      C  NaN  20 to 30
98  81.462898  1.833087  22.679948      A  NaN  20 to 30
99  80.942447  1.476627  29.979698      C  NaN  20 to 30

[100 rows x 6 columns]


In [ ]:
#QUESTION 9

Q9 = Q8.copy() #copies Q8

for i in range(100):
    Q9.at[i, "BMI"] = Q9.at[i, "Weight"] / (pow(Q9.at[i, "Height"], 2)) #calculates BMI for each index

print(Q9)

       Weight    Height        Age Gender        BMI Age group
0   80.926939  1.311158  19.340225      C  47.074228  Under 20
1   80.823257  1.753769  16.441907      C  26.277964  Under 20
2   80.188001  2.049443  20.067738      B  19.091402  20 to 30
3   81.258834  1.635225  27.433182      A  30.388923  20 to 30
4   80.675329  1.897708  28.800292      B  22.401755  20 to 30
..        ...       ...        ...    ...        ...       ...
95  80.778257  1.893169  20.096202      B  22.538025  20 to 30
96  81.001885  1.523962  24.684758      C  34.877610  20 to 30
97  81.022949  1.717237  20.507163      C  27.475637  20 to 30
98  81.462898  1.833087  22.679948      A  24.243411  20 to 30
99  80.942447  1.476627  29.979698      C  37.122279  20 to 30

[100 rows x 6 columns]


In [ ]:
#QUESTION 10

def function_Q10(f_weight, f_height):
    f_BMI = f_weight / pow(f_height, 2) #height / weight^2
    return f_BMI #returns calculated BMI

print(function_Q10(w.weight, h.height)) #proof that it works





[47.07422834 26.27796444 19.09140184 30.38892285 22.40175513 19.30855694
 42.23015116 27.61089417 20.31924451 28.77904171 20.22637493 32.68886087
 33.46556677 24.90872092 42.65482411 22.79788163 23.07321364 28.53123294
 32.17656991 28.43832603 22.97905061 29.39062458 23.77763819 31.18097968
 20.07315039 30.55977796 29.21837803 25.52040611 31.90610627 20.2263259
 26.56380882 17.14710875 25.03670685 22.70485486 26.21141982 29.90528179
 33.3394762  21.37086742 18.76988146 27.87312211 19.08807535 24.05356647
 28.05224704 35.25671391 35.47797622 22.24836333 19.28074443 29.78319335
 15.80462861 39.95696746 29.6093598  23.84464947 33.48980128 31.59111094
 26.28294221 40.55103373 34.44052832 23.19909287 66.81780024 23.98294142
 25.43139064 18.53675524 26.54571794 27.27121441 28.77413477 30.11411346
 21.09330591 28.74577411 28.14360132 30.99764661 28.38850084 24.65117298
 19.33827863 24.79255491 24.91410145 14.44437076 27.30491023 19.27633302
 22.06107279 21.6282153  20.69201951 24.66895589 26.

In [ ]:
#QUESTION 11

def function_Q11(Q9, gender):
    sum = 0 #BMI sum for gender
    num = 0 #total count of that gender

    for i in range(100):
        if Q9.at[i, "Gender"] == gender: 
            sum += Q9.at[i,"BMI"] #adds to sum
            num += 1 #increments count
    
    return sum / num #Average BMI

print(function_Q11(Q9, "A")) #proof that it works



26.145614245195038
