In [3]:
import numpy as np
import pandas as pd
import matplotlib as plot

In [4]:
#QUESTION 1

#Assigns x
x = 26

#Assigns y array
y = [2, 36, 1, 98, 124]

#Assigns z as x * y
z = [2 * x, 36 * x, 1 * x, 98 * x, 124 * x]

print(z)

[52, 936, 26, 2548, 3224]


In [5]:
#QUESTION 2

#Assigns variables
x = 21
y = 2
Q2_1 = [x]
Q2_2 = [y]

#Builds series array from 21 to 400
while x < 400:
    x = Q2_1[-1] + 1
    Q2_1 = Q2_1 + [x]

#Builds series array from 2 to -35
while y > -35:
    y = Q2_2[-1] - 1
    Q2_2 = Q2_2 + [y]

print(Q2_1)
print(Q2_2)

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236

In [6]:
#QUESTION 3

#Assigns variables
x = -3
Q3 = [x]

#Builds series array from -3 to 9
while x < 9:
    x = Q3[-1] + 0.1
    x = round(x, 1) #Ensures x stays at 1 decimal point
    Q3 = Q3 + [x]

print(Q3)

[-3, -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2.0, -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0]


In [7]:
#QUESTION 4

i = 0 #index
n = len(Q3) #determines max random number
Q4 = np.zeros((100,20)) #makes 

while i < 100: #Repeats the random sampling 100 times
    j = 0 #index

    while j < 20: #randomly samples 20 elements from Q3
        Q4[i][j] = Q3[np.random.randint(0,len(Q3))]
        j += 1
    
    i += 1

print(Q4)


[[-1.1  4.7  2.8 ...  0.8  5.2 -3. ]
 [-0.4  7.3 -3.  ... -1.2  0.8  1.1]
 [-0.5 -1.6 -1.3 ... -0.1  1.3  5.9]
 ...
 [ 0.4  4.2  1.4 ... -0.7  3.2 -2. ]
 [ 8.2 -1.9  2.2 ... -0.2  6.4  7.8]
 [ 2.   0.3  3.1 ...  2.1  0.5  1.7]]


In [8]:
#QUESTION 5

#I'm interpreting this as needing a 6x6 dataframe with the columns titled by the days and the rows titled by the numbers.

t = ["mon", "tue", "wed", "thu", "fri", "sat"] #column titles
m = [90, 80, 50, 20, 5, 20] #row titles

Q5 = pd.DataFrame(np.zeros((6,6)), m, t) #creates a 6x6 dataframe that uses the information in lists t & m

print(Q5)

    mon  tue  wed  thu  fri  sat
90  0.0  0.0  0.0  0.0  0.0  0.0
80  0.0  0.0  0.0  0.0  0.0  0.0
50  0.0  0.0  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0


In [9]:
#QUESTION 6

class w: #weight stats
    weight = np.empty(100) #creates empty array
    mean = 81
    sd = 0.26
    units = "kg"

class h: #height stats
    height = np.empty(100) #creates empty array
    mean = 1.76
    sd = 0.22
    units = "m"

class a: #age stats
    age = np.empty(100) #creates empty array
    mean = 25
    sd = 5
    units = "years"

gender = np.empty(100, str)
genderOpts = ["A", "B", "C"]

for i in range(100):
    w.weight[i] = np.random.normal(w.mean, w.sd)
    h.height[i] = np.random.normal(h.mean, h.sd)
    a.age[i] = np.random.normal(a.mean, a.sd)
    gender[i] = genderOpts[np.random.randint(0,len(genderOpts))] #randomly samples from list ["A", "B", "C"]

print(w.weight)
print(h.height)
print(a.age)
print(gender)
    

[81.13246068 80.97890971 81.2685339  80.30974824 81.71127474 81.00668688
 81.11255834 80.89337742 80.68297221 80.97853388 81.097646   81.02687363
 81.28915683 80.96537718 80.48657497 80.97543212 80.91206629 81.47619388
 80.85814516 81.1741729  80.89247775 80.6686094  81.06607583 80.8942877
 80.54036706 80.78999411 81.06879436 81.28176466 81.00689388 80.84456575
 81.05914379 81.01729361 80.59389353 81.03123898 81.23824264 81.33227423
 80.72015925 81.26524223 81.09763453 81.34964577 81.5263502  81.33843419
 81.83297072 80.83128248 80.7939477  81.29747287 80.55110876 81.15312518
 81.40642612 81.00495508 80.83291288 80.87945745 80.91757276 81.22570382
 80.80911293 80.8872787  80.35504732 81.17862682 81.40571532 80.97542242
 81.13630456 80.77757089 80.54638652 81.50459907 81.11923485 80.53271302
 81.23355723 81.25688358 81.13589387 81.19767334 81.02476145 80.74173417
 81.05551094 80.80678742 81.05750678 80.97924875 81.02726916 81.069531
 80.73902394 80.8230274  80.59570867 81.22277611 80.78

In [10]:
#QUESTION 7

BMI = np.full(100, np.nan) #generates 100 element array of NaN

Q7 = pd.DataFrame({ #Organizes the data by column in this dataframe
    "Weight": w.weight, 
    "Height": h.height, 
    "Age": a.age, 
    "Gender": gender,
    "BMI": BMI
    }
)

print(Q7)

       Weight    Height        Age Gender  BMI
0   81.132461  1.646114  19.214545      B  NaN
1   80.978910  1.886439  20.337469      A  NaN
2   81.268534  1.956816  34.276669      C  NaN
3   80.309748  1.367808  21.957426      C  NaN
4   81.711275  1.426046  25.522465      A  NaN
..        ...       ...        ...    ...  ...
95  81.442609  2.246533  23.374274      A  NaN
96  80.979370  1.534936  16.585969      C  NaN
97  81.041699  2.048007  24.432189      A  NaN
98  80.847598  1.784030  21.167906      C  NaN
99  81.123824  1.844467  26.863271      A  NaN

[100 rows x 5 columns]


In [ ]:
#QUESTION 8

AgeGroup = np.empty(100, bool) #creates array of boolean values

for i in range(100): 
    temp = Q7.at[i, "Age"] #references the ages 1 by 1

    if temp < 20 or temp > 30: #if younger than 20 or older than 30
        AgeGroup[i] = True
    else: #if between ages 20 and 30
        AgeGroup[i] = False

Q8 = Q7.copy() #copies Q7
Q8["Age group"] = AgeGroup #Adds column titled "Age group" to Q8

print(Q8)

       Weight    Height        Age Gender  BMI  Age group
0   81.132461  1.646114  19.214545      B  NaN       True
1   80.978910  1.886439  20.337469      A  NaN      False
2   81.268534  1.956816  34.276669      C  NaN       True
3   80.309748  1.367808  21.957426      C  NaN      False
4   81.711275  1.426046  25.522465      A  NaN      False
..        ...       ...        ...    ...  ...        ...
95  81.442609  2.246533  23.374274      A  NaN      False
96  80.979370  1.534936  16.585969      C  NaN       True
97  81.041699  2.048007  24.432189      A  NaN      False
98  80.847598  1.784030  21.167906      C  NaN      False
99  81.123824  1.844467  26.863271      A  NaN      False

[100 rows x 6 columns]


In [12]:
#QUESTION 9

Q9 = Q8.copy() #copies Q8

for i in range(100):
    Q9.at[i, "BMI"] = Q9.at[i, "Weight"] / (pow(Q9.at[i, "Height"], 2)) #calculates BMI for each index

print(Q9)

       Weight    Height        Age Gender        BMI  Age group
0   81.132461  1.646114  19.214545      B  29.941573       True
1   80.978910  1.886439  20.337469      A  22.755492      False
2   81.268534  1.956816  34.276669      C  21.223769       True
3   80.309748  1.367808  21.957426      C  42.925762      False
4   81.711275  1.426046  25.522465      A  40.180474      False
..        ...       ...        ...    ...        ...        ...
95  81.442609  2.246533  23.374274      A  16.137123      False
96  80.979370  1.534936  16.585969      C  34.371153       True
97  81.041699  2.048007  24.432189      A  19.321719      False
98  80.847598  1.784030  21.167906      C  25.401711      False
99  81.123824  1.844467  26.863271      A  23.845524      False

[100 rows x 6 columns]


In [13]:
#QUESTION 10

def function_Q10(f_weight, f_height):
    f_BMI = f_weight / pow(f_height, 2) #height / weight^2
    return f_BMI #returns calculated BMI

print(function_Q10(w.weight, h.height)) #proof that it works





[29.94157272 22.75549206 21.22376869 42.92576174 40.1804736  34.84735664
 40.00927607 21.66549238 21.27660077 18.34500466 26.8528458  32.01222142
 23.78550325 23.41554063 24.87061883 27.39045308 25.35702519 22.59809097
 24.98309492 19.39424403 24.29140746 21.83515781 56.16926655 29.7409098
 25.74962821 26.00441521 27.27278377 38.38980165 28.96489744 29.20673378
 27.61154285 37.36067978 24.92767004 24.09421167 38.66931995 20.89670614
 25.95721059 28.40285178 21.03093237 41.3821204  20.72219651 20.74975049
 25.82156134 22.66485745 21.75120592 32.57389682 24.89414277 33.83022129
 27.47058308 54.20509417 33.66411168 44.68900794 26.41949777 25.28100083
 27.27449572 24.04482243 29.82516836 35.47427497 30.49164385 29.86570018
 24.77356551 17.97397036 32.84061386 23.38517573 22.39886459 22.25543287
 29.02481238 17.94984951 20.56887645 15.88789731 25.3014462  25.02477738
 20.62433899 20.63537769 27.71495147 30.84841289 32.49034624 45.7180358
 27.9965924  33.46415627 28.17222291 21.69940962 36.8

In [14]:
#QUESTION 11

def function_Q11(Q9, gender):
    sum = 0 #BMI sum for gender
    num = 0 #total count of that gender

    for i in range(100):
        if Q9.at[i, "Gender"] == gender: 
            sum += Q9.at[i,"BMI"] #adds to sum
            num += 1 #increments count
    
    return sum / num #Average BMI

print(function_Q11(Q9, "A")) #proof that it works



28.343430654681036


In [15]:
#QUESTION 12

Q12 = Q9.copy() #copies Q9
BMIc = np.zeros(100)

for i in range(100):
    if Q12.at[i, "BMI"] == True: #if they are younger than 20 or older than 30
        BMIc[i] = 1.1 * Q12.at[i, "BMI"]
    else:
        BMIc[i] = Q12.at[i, "BMI"]

Q12["BMIc"] = BMIc

print(Q12)

       Weight    Height        Age Gender        BMI  Age group       BMIc
0   81.132461  1.646114  19.214545      B  29.941573       True  29.941573
1   80.978910  1.886439  20.337469      A  22.755492      False  22.755492
2   81.268534  1.956816  34.276669      C  21.223769       True  21.223769
3   80.309748  1.367808  21.957426      C  42.925762      False  42.925762
4   81.711275  1.426046  25.522465      A  40.180474      False  40.180474
..        ...       ...        ...    ...        ...        ...        ...
95  81.442609  2.246533  23.374274      A  16.137123      False  16.137123
96  80.979370  1.534936  16.585969      C  34.371153       True  34.371153
97  81.041699  2.048007  24.432189      A  19.321719      False  19.321719
98  80.847598  1.784030  21.167906      C  25.401711      False  25.401711
99  81.123824  1.844467  26.863271      A  23.845524      False  23.845524

[100 rows x 7 columns]
