In [4]:
import numpy as np
import pandas
import matplotlib as plot

In [5]:
#QUESTION 1

#Assigns x
x = 26

#Assigns y array
y = [2, 36, 1, 98, 124]

#Assigns z as x * y
z = [2 * x, 36 * x, 1 * x, 98 * x, 124 * x]

print(z)

[52, 936, 26, 2548, 3224]


In [6]:
#QUESTION 2

#Assigns variables
x = 21
y = 2
Q2_1 = [x]
Q2_2 = [y]

#Builds series array from 21 to 400
while x < 400:
    x = Q2_1[-1] + 1
    Q2_1 = Q2_1 + [x]

#Builds series array from 2 to -35
while y > -35:
    y = Q2_2[-1] - 1
    Q2_2 = Q2_2 + [y]

print(Q2_1)
print(Q2_2)

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236

In [7]:
#QUESTION 3

#Assigns variables
x = -3
Q3 = [x]

#Builds series array from -3 to 9
while x < 9:
    x = Q3[-1] + 0.1
    x = round(x, 1) #Ensures x stays at 1 decimal point
    Q3 = Q3 + [x]

print(Q3)

[-3, -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2.0, -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0]


In [ ]:
#QUESTION 4

i = 0 #index
n = len(Q3) #determines max random number
Q4 = np.zeros((100,20)) #makes 

while i < 100: #Repeats the random sampling 100 times
    j = 0 #index

    while j < 20: #randomly samples 20 elements from Q3
        Q4[i][j] = Q3[np.random.randint(0,len(Q3) - 1)]
        j += 1
    
    i += 1

print(Q4)


[[ 1.5  3.1  7.5 ...  2.   4.3  2.4]
 [-3.  -2.4  4.9 ...  7.8 -0.2 -2.5]
 [ 1.   1.2  6.  ... -0.5 -2.7  3.7]
 ...
 [-2.5  2.1  7.9 ...  0.8  5.7  4.6]
 [ 2.9  0.5  2.9 ...  7.4  1.2  2.1]
 [-2.7 -1.6  4.7 ...  4.5  1.9  3.6]]


In [ ]:
#QUESTION 5

